In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy

In [3]:
df=pd.read_csv("dataset.txt")
df

Country   Age   Salary Purchesed
0    India  38.0  68000.0        No
1    Fance  43.0  45000.0       Yes
2  Germany  30.0  54000.0        No
3   France  48.0  68000.0        No
4  Germany  40.0      NaN       Yes
5    India  35.0  58000.0       Yes
6  Germany   NaN  53000.0        No
7   France  49.0  79000.0       Yes
8    India  50.0  88000.0        No
9   France  37.0  77000.0       Yes

In [23]:
type(df)
df.size
df.shape
len(df)
len(df.columns)
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchesed  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


Age        Salary
count   9.000000      9.000000
mean   41.111111  65555.555556
std     6.900081  14134.276698
min    30.000000  45000.000000
25%    37.000000  54000.000000
50%    40.000000  68000.000000
75%    48.000000  77000.000000
max    50.000000  88000.000000

In [70]:
# extracting independent and dependent variable
# extracting independent variable we use iloc[] method
x=df.iloc[:,:-1].values
x

array([['India', 38.0, 68000.0],
       ['Fance', 43.0, 45000.0],
       ['Germany', 30.0, 54000.0],
       ['France', 48.0, 68000.0],
       ['Germany', 40.0, nan],
       ['India', 35.0, 58000.0],
       ['Germany', nan, 53000.0],
       ['France', 49.0, 79000.0],
       ['India', 50.0, 88000.0],
       ['France', 37.0, 77000.0]], dtype=object)

In [131]:
# extracting dependent variable we use iloc[] method
y=df.iloc[:,3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [132]:
#handling missing data (Replacing missing data with the mean value)  
#from sklearn.preprocessing import Imputer 
from sklearn.impute import SimpleImputer

impute= SimpleImputer(missing_values =np.nan, strategy='mean')  
#Fitting imputer object to the independent variables x.   
imputer= impute.fit(x[:,1:3])  
#Replacing missing data with the calculated mean value  
x[:,1:3]= imputer.transform(x[:,1:3])  
x

array([[1., 0., 0., ..., 1., 1., 0.],
       [0., 1., 1., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 1., 0.]])

In [133]:
from sklearn.preprocessing import LabelEncoder
encoded=LabelEncoder()
x[:,0]=encoded.fit_transform(x[:,0])
x

array([[1., 0., 0., ..., 1., 1., 0.],
       [0., 1., 1., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 1., 0.]])

In [134]:
#for Country Variable  
from sklearn.preprocessing import LabelEncoder, OneHotEncoder  
label_encoder_x= LabelEncoder()  
x[:, 0]= label_encoder_x.fit_transform(x[:, 0])  
#Encoding for dummy variables  
onehot_encoder= OneHotEncoder()    
x= onehot_encoder.fit_transform(x).toarray()  
x

array([[0., 1., 1., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       [0., 1., 1., ..., 1., 1., 0.],
       ...,
       [0., 1., 1., ..., 1., 1., 0.],
       [0., 1., 1., ..., 0., 0., 1.],
       [0., 1., 1., ..., 1., 1., 0.]])

In [135]:
labelencoder_y= LabelEncoder()  
y= labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [140]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
#x_train
#x_test
#y_train
#y_test

In [142]:
from sklearn.preprocessing import StandardScaler
stdc=StandardScaler()
x_train=stdc.fit_transform(x_train)
x_train

array([[-0.37796447,  0.37796447,  0.37796447, ...,  0.        ,
         0.        ,  0.        ],
       [-0.37796447,  0.37796447,  0.37796447, ...,  0.        ,
         0.        ,  0.        ],
       [ 2.64575131, -2.64575131, -2.64575131, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.37796447,  0.37796447,  0.37796447, ...,  0.        ,
         0.        ,  0.        ],
       [-0.37796447,  0.37796447,  0.37796447, ...,  0.        ,
         0.        ,  0.        ],
       [-0.37796447,  0.37796447,  0.37796447, ...,  0.        ,
         0.        ,  0.        ]])

In [143]:
x_test=stdc.fit_transform(x_test)
x_test

array([[ 0.,  0.,  0., ...,  1.,  1., -1.],
       [ 0.,  0.,  0., ..., -1., -1.,  1.]])

In [ ]:
stdc.fit